// DKC2 world map font — ground truth, NOT a guess.
//
// The world maps draw their level names straight into OAM. There is no ROM
// animation entry for them (p4plus2's sprites.txt has none) and no VRAM still
// dump contains them, so the letters exist only as runtime captures. What makes
// the mapping verifiable rather than guessed is that the names are READABLE:
// each glyph was confirmed by reading whole level names back in plain text.
//
// A glyph is 8x16 = two stacked tiles (top at y, bottom at y+8), addressed by
// their content hashes. PUNCTUATION IS SINGLE-ROW — bottom is null there. That
// exception cost the apostrophe once already, when a hard pairing rule dropped
// every one-row glyph on the floor.
//
// Palette 6 on every world map. Extend by reading an unknown glyph's context:
// the viewer prints '?' for anything not in here, with the surrounding letters.
//
// Generated by scratchpad/gen_font_gt.js — 28 glyphs confirmed 2026-07-31,
// "'", "-" and "V" derived 2026-08-03. 31 glyphs = the complete alphabet.

const DKC2_MAP_FONT = [
 {
  "char": "K",
  "top": "90AD93B708E7838A",
  "bottom": "E4C06FFDB50D46FB",
  "count": 39
 },
 {
  "char": "N",
  "top": "62F453FA23B08DD0",
  "bottom": "3DE5FE3A240216D7",
  "count": 32
 },
 {
  "char": "R",
  "top": "34D971FF1D6F9E93",
  "bottom": "0455736232D03EF3",
  "count": 32
 },
 {
  "char": "O",
  "top": "8F79BDE2EA3319A7",
  "bottom": "F926344A0A9BE426",
  "count": 30
 },
 {
  "char": "L",
  "top": "8A2BCBA010B53575",
  "bottom": "768BD5F2EEF6EB29",
  "count": 25
 },
 {
  "char": "B",
  "top": "75796AE1E39C15D5",
  "bottom": "8F6F41AA2A6E6582",
  "count": 24
 },
 {
  "char": "U",
  "top": "D358051B581248C9",
  "bottom": "EC04C5D43826562D",
  "count": 22
 },
 {
  "char": "A",
  "top": "C1A78F029CE86E59",
  "bottom": "9885C006A2B697DB",
  "count": 21
 },
 {
  "char": "T",
  "top": "EED1CDFC2DEA7878",
  "bottom": "541EC55B9AE1ED41",
  "count": 19
 },
 {
  "char": "E",
  "top": "6D92B50584287B66",
  "bottom": "F4C293BEB7D49DA0",
  "count": 19
 },
 {
  "char": "G",
  "top": "9AD8C5DADEC5E661",
  "bottom": "E5B70439EC042A75",
  "count": 16
 },
 {
  "char": "P",
  "top": "226533796062C7C3",
  "bottom": "6CB56B76AFAA0DAB",
  "count": 14
 },
 {
  "char": "W",
  "top": "A23298C528092898",
  "bottom": "2A3EB0170FE7C209",
  "count": 14
 },
 {
  "char": "!",
  "top": "CA092B966EC7BD75",
  "bottom": "0A56735398E1B2F7",
  "count": 13
 },
 {
  "char": "[DK1]",
  "top": "AD95D8E5BF878F22",
  "bottom": "00C5B7929066F907",
  "count": 13
 },
 {
  "char": "M",
  "top": "37C244620B2664DE",
  "bottom": "F817F7B84C18D92E",
  "count": 13
 },
 {
  "char": "H",
  "top": "26ADFAD70DF950C0",
  "bottom": "19B4E08B2DC61D25",
  "count": 12
 },
 {
  "char": "C",
  "top": "7CB7A833CADEFCBB",
  "bottom": "818BABC374201D20",
  "count": 12
 },
 {
  "char": "I",
  "top": "8DFFB105EB63571A",
  "bottom": "C77E8EE660D83F03",
  "count": 12
 },
 {
  "char": "D",
  "top": "D270D76DCEA3EFFA",
  "bottom": "802C25A768F3F2B7",
  "count": 11
 },
 {
  "char": "[DK2]",
  "top": "D367351B2AEAFE87",
  "bottom": "2151C5CE4546E8F5",
  "count": 10
 },
 {
  "char": "S",
  "top": "B54DCBA4476C53D6",
  "bottom": "C274B059B0A1CD1D",
  "count": 10
 },
 {
  "char": "Y",
  "top": "DA4AD35A7B3FAB89",
  "bottom": "E7214A77C666B7BD",
  "count": 6
 },
 {
  "char": "F",
  "top": "94018DFB536CA45A",
  "bottom": "D6DEE4C00FAE5AAB",
  "count": 5
 },
 {
  "char": "Z",
  "top": "70FBA9E4BD7E2DFB",
  "bottom": "B300CA526CCB5C0A",
  "count": 4
 },
 {
  "char": "Q",
  "top": "F2A47380E0779301",
  "bottom": "F59D112C2B8B9DF8",
  "count": 3
 },
 {
  "char": "J",
  "top": "544DB2525DEFBFA9",
  "bottom": "43DB60B22BB45F23",
  "count": 2
 },
 {
  "char": "X",
  "top": "166D61FDDA5F0295",
  "bottom": "B7E6DBF48228F7EC",
  "count": 1
 },
 {
  "char": "'",
  "top": "E7B7C0F1CBBEE6C1",
  "bottom": null,
  "count": 6,
  "note": "einzeilig; belegt in SWANKY'S, LUBBA'S, KROW'S, JAW'S"
 },
 {
  "char": "-",
  "top": "BCF61FDA52C9D363",
  "bottom": "AF750CD8D7718ED8",
  "count": 1,
  "note": "belegt in HOT-HEAD HOP"
 },
 {
  "char": "V",
  "top": "4896BAF004A466E2",
  "bottom": "DE1CDFFED05D5615",
  "count": 1,
  "note": "CLAPPER'S CAVERN (K. Rool's Keep). Die Zeile las sich C L _ P _ E R … C _ V _ R N — C, R und N sitzen passend, und das erste C hat denselben Hash wie das C von CAVERN. Gerendert ein eindeutiges V."
 }
];

// Known to exist but NOT yet mapped to hashes. Listed so the font page can SHOW
// the gap: a blank slot asks the question, an absent slot does not.
// Empty now — the alphabet is complete.
const DKC2_MAP_FONT_MISSING = [];
